splash = false

preload = /home/covmoore/.config/themes/chill-vibes/images/green_trees.jpg

wallpaper {
    monitor =
    path = /home/covmoore/.config/themes/chill-vibes/images/green_trees.jpg
    fit_mode = cover
}
