# TEXT COLOR
$color0 = #0a0908

# WIDGET COLOR
$color1 = #5e503f

# FOREGROUND COLOR
$color2 = #c6ac8f

# ACTIVE WIDGET
$color3 = #432818

# BACKGROUND COLOR
$color4 = #22333b

# CURSOR COLOR
$color5 = #333d29

# TERMINAL BACKGROUND
$color6 = #22333b

# TERMINAL FOREGROUND
$color7 = #c6ac8f
