# TEXT COLOR
$text_color = #0a0908

# WIDGET COLOR
$widget_color = #5e503f

# FOREGROUND COLOR
$foreground_color = #c6ac8f

# ACTIVE WIDGET
$active_widget = #432818

# BACKGROUND COLOR
$background_color = #22333b

# CURSOR COLOR
$cursor_color = #333d29

# TERMINAL BACKGROUND
$terminal_background = #22333b

# TERMINAL FOREGROUND
$terminal_foreground = #c6ac8f

# WALLPAPER IMAGE
$wallpaper = $HOME/.config/themes/chill-vibes/images/green_trees.jpg


#HYPRLOCK VARIABLES
$greeting_color= #c6ac8f
$input_border_color= #c6ac8f
$failed_input_border_color= #9b1515
$time_color= #5e503f
$date_color= #104a65
$greeting_message= GOING FOR A LITTLE NAP...

